# Generated by Django 4.2.4 on 2024-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=100),
        ),
    ]
