# Generated by Django 4.2.4 on 2024-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_entry', '0002_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
